@echo off
setlocal enabledelayedexpansion

echo ====================================
echo   Crassus 2.5 — First Time Setup
echo ====================================
echo.

REM ------------------------------------------------------------------
REM Pre-flight: Python 3.10+
REM ------------------------------------------------------------------
where python >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Python is not installed or not on PATH.
    echo         Download it from https://python.org
    echo         Make sure to check "Add Python to PATH" during install.
    exit /b 1
)

for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYVER=%%v
for /f "tokens=1,2 delims=." %%a in ("%PYVER%") do (
    set PYMAJOR=%%a
    set PYMINOR=%%b
)

if %PYMAJOR% lss 3 (
    echo [ERROR] Python 3.10+ is required. Found Python %PYVER%.
    echo         Download it from https://python.org
    exit /b 1
)
if %PYMAJOR% equ 3 if %PYMINOR% lss 10 (
    echo [ERROR] Python 3.10+ is required. Found Python %PYVER%.
    echo         Download it from https://python.org
    exit /b 1
)
echo [OK] Python %PYVER% detected.

REM ------------------------------------------------------------------
REM Pre-flight: pip
REM ------------------------------------------------------------------
python -m pip --version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] pip is not available. Run: python -m ensurepip --upgrade
    exit /b 1
)
echo [OK] pip is available.

REM ------------------------------------------------------------------
REM Virtual environment
REM ------------------------------------------------------------------
if not exist ".venv" (
    echo.
    echo Creating virtual environment...
    python -m venv .venv
    if %ERRORLEVEL% neq 0 (
        echo [ERROR] Failed to create virtual environment.
        exit /b 1
    )
    echo [OK] Virtual environment created in .venv\
) else (
    echo [OK] Virtual environment already exists.
)

call .venv\Scripts\activate

REM ------------------------------------------------------------------
REM Install dependencies
REM ------------------------------------------------------------------
echo.
echo Installing function dependencies...
pip install -r function_app\requirements.txt --quiet
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Failed to install function_app dependencies.
    exit /b 1
)
echo [OK] Function dependencies installed.

echo Installing dashboard dependencies...
pip install flask python-dotenv alpaca-py --quiet
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Failed to install dashboard dependencies.
    exit /b 1
)
echo [OK] Dashboard dependencies installed.

echo Installing test dependencies...
pip install pytest --quiet
echo [OK] Test dependencies installed.

REM ------------------------------------------------------------------
REM Credential prompts
REM ------------------------------------------------------------------
echo.
echo ====================================
echo   Credential Setup
echo ====================================
echo This will set up your trading environment.
echo You'll need your Alpaca API keys (from https://app.alpaca.markets)
echo.

set /p ALPACA_KEY="Enter your Alpaca API Key: "
if "!ALPACA_KEY!"=="" (
    echo [ERROR] API Key cannot be empty.
    exit /b 1
)

set /p ALPACA_SECRET="Enter your Alpaca Secret Key: "
if "!ALPACA_SECRET!"=="" (
    echo [ERROR] Secret Key cannot be empty.
    exit /b 1
)

set /p WEBHOOK_TOKEN="Enter a webhook auth token (or press Enter to auto-generate one): "
if "!WEBHOOK_TOKEN!"=="" (
    REM Generate a random 32-char hex token using Python
    for /f %%t in ('python -c "import secrets; print(secrets.token_hex(16))"') do set WEBHOOK_TOKEN=%%t
    echo [OK] Auto-generated webhook token: !WEBHOOK_TOKEN!
)

REM ------------------------------------------------------------------
REM Generate .env
REM ------------------------------------------------------------------
echo.
echo Writing .env file...
(
echo # ---------------------------------------------------------------------------
echo # Crassus 2.5 -- Environment Configuration
echo # Generated by setup.bat
echo # ---------------------------------------------------------------------------
echo.
echo # Alpaca API
echo ALPACA_API_KEY=!ALPACA_KEY!
echo ALPACA_SECRET_KEY=!ALPACA_SECRET!
echo WEBHOOK_AUTH_TOKEN=!WEBHOOK_TOKEN!
echo ALPACA_PAPER=true
echo DEFAULT_STOCK_QTY=1
echo.
echo # Strategy: bollinger_mean_reversion
echo BMR_STOCK_TP_PCT=0.2
echo BMR_STOCK_SL_PCT=0.1
echo BMR_STOCK_STOP_LIMIT_PCT=0.15
echo BMR_OPTIONS_TP_PCT=20.0
echo BMR_OPTIONS_SL_PCT=10.0
echo.
echo # Strategy: lorentzian_classification
echo LC_STOCK_TP_PCT=1.0
echo LC_STOCK_SL_PCT=0.8
echo LC_STOCK_STOP_LIMIT_PCT=0.9
echo LC_OPTIONS_TP_PCT=50.0
echo LC_OPTIONS_SL_PCT=40.0
echo.
echo # Options screening
echo OPTIONS_DTE_MIN=14
echo OPTIONS_DTE_MAX=45
echo OPTIONS_DELTA_MIN=0.30
echo OPTIONS_DELTA_MAX=0.70
echo OPTIONS_MIN_OI=100
echo OPTIONS_MIN_VOLUME=10
echo OPTIONS_MAX_SPREAD_PCT=5.0
echo OPTIONS_MIN_PRICE=0.50
echo OPTIONS_MAX_PRICE=50.0
echo.
echo # Greeks / Yahoo / Risk
echo RISK_FREE_RATE=0.05
echo YAHOO_ENABLED=true
echo YAHOO_RETRY_COUNT=5
echo YAHOO_BACKOFF_BASE=2
echo MAX_DOLLAR_RISK=50.0
) > .env
echo [OK] .env created.

REM ------------------------------------------------------------------
REM Generate function_app/local.settings.json
REM ------------------------------------------------------------------
echo Writing function_app\local.settings.json...
(
echo {
echo   "IsEncrypted": false,
echo   "Values": {
echo     "FUNCTIONS_WORKER_RUNTIME": "python",
echo     "AzureWebJobsStorage": "UseDevelopmentStorage=true",
echo     "ALPACA_API_KEY": "!ALPACA_KEY!",
echo     "ALPACA_SECRET_KEY": "!ALPACA_SECRET!",
echo     "WEBHOOK_AUTH_TOKEN": "!WEBHOOK_TOKEN!",
echo     "ALPACA_PAPER": "true"
echo   },
echo   "Host": {
echo     "CORS": "*"
echo   }
echo }
) > function_app\local.settings.json
echo [OK] function_app\local.settings.json created.

REM ------------------------------------------------------------------
REM Done
REM ------------------------------------------------------------------
echo.
echo ====================================
echo   Setup complete!
echo ====================================
echo.
echo To launch the dashboard:
echo   run_dashboard.bat
echo.
echo To run the trading function locally:
echo   run_crassus.bat
echo.
echo To run tests:
echo   run_tests.bat
echo.

endlocal
