#!/usr/bin/env bash
set -e

echo "===================================="
echo "  Crassus 2.5 — First Time Setup"
echo "===================================="
echo

# ------------------------------------------------------------------
# Pre-flight: Python 3.10+
# ------------------------------------------------------------------
if ! command -v python3 &>/dev/null; then
    echo "[ERROR] Python 3 is not installed."
    echo "        macOS:  brew install python@3.11"
    echo "        Linux:  sudo apt install python3 python3-venv python3-pip"
    exit 1
fi

PYVER=$(python3 --version 2>&1 | awk '{print $2}')
PYMAJOR=$(echo "$PYVER" | cut -d. -f1)
PYMINOR=$(echo "$PYVER" | cut -d. -f2)

if [ "$PYMAJOR" -lt 3 ] || ([ "$PYMAJOR" -eq 3 ] && [ "$PYMINOR" -lt 10 ]); then
    echo "[ERROR] Python 3.10+ is required. Found Python $PYVER."
    exit 1
fi
echo "[OK] Python $PYVER detected."

# ------------------------------------------------------------------
# Pre-flight: pip
# ------------------------------------------------------------------
if ! python3 -m pip --version &>/dev/null; then
    echo "[ERROR] pip is not available. Run: python3 -m ensurepip --upgrade"
    exit 1
fi
echo "[OK] pip is available."

# ------------------------------------------------------------------
# Virtual environment
# ------------------------------------------------------------------
if [ ! -d ".venv" ]; then
    echo
    echo "Creating virtual environment..."
    python3 -m venv .venv
    echo "[OK] Virtual environment created in .venv/"
else
    echo "[OK] Virtual environment already exists."
fi

source .venv/bin/activate

# ------------------------------------------------------------------
# Install dependencies
# ------------------------------------------------------------------
echo
echo "Installing function dependencies..."
pip install -r function_app/requirements.txt --quiet
echo "[OK] Function dependencies installed."

echo "Installing dashboard dependencies..."
pip install flask python-dotenv alpaca-py --quiet
echo "[OK] Dashboard dependencies installed."

echo "Installing test dependencies..."
pip install pytest --quiet
echo "[OK] Test dependencies installed."

# ------------------------------------------------------------------
# Credential prompts
# ------------------------------------------------------------------
echo
echo "===================================="
echo "  Credential Setup"
echo "===================================="
echo "This will set up your trading environment."
echo "You'll need your Alpaca API keys (from https://app.alpaca.markets)"
echo

read -rp "Enter your Alpaca API Key: " ALPACA_KEY
if [ -z "$ALPACA_KEY" ]; then
    echo "[ERROR] API Key cannot be empty."
    exit 1
fi

read -rp "Enter your Alpaca Secret Key: " ALPACA_SECRET
if [ -z "$ALPACA_SECRET" ]; then
    echo "[ERROR] Secret Key cannot be empty."
    exit 1
fi

read -rp "Enter a webhook auth token (or press Enter to auto-generate one): " WEBHOOK_TOKEN
if [ -z "$WEBHOOK_TOKEN" ]; then
    WEBHOOK_TOKEN=$(python3 -c "import secrets; print(secrets.token_hex(16))")
    echo "[OK] Auto-generated webhook token: $WEBHOOK_TOKEN"
fi

# ------------------------------------------------------------------
# Generate .env
# ------------------------------------------------------------------
echo
echo "Writing .env file..."
cat > .env << ENVEOF
# ---------------------------------------------------------------------------
# Crassus 2.5 -- Environment Configuration
# Generated by setup.sh
# ---------------------------------------------------------------------------

# Alpaca API
ALPACA_API_KEY=$ALPACA_KEY
ALPACA_SECRET_KEY=$ALPACA_SECRET
WEBHOOK_AUTH_TOKEN=$WEBHOOK_TOKEN
ALPACA_PAPER=true
DEFAULT_STOCK_QTY=1

# Strategy: bollinger_mean_reversion
BMR_STOCK_TP_PCT=0.2
BMR_STOCK_SL_PCT=0.1
BMR_STOCK_STOP_LIMIT_PCT=0.15
BMR_OPTIONS_TP_PCT=20.0
BMR_OPTIONS_SL_PCT=10.0

# Strategy: lorentzian_classification
LC_STOCK_TP_PCT=1.0
LC_STOCK_SL_PCT=0.8
LC_STOCK_STOP_LIMIT_PCT=0.9
LC_OPTIONS_TP_PCT=50.0
LC_OPTIONS_SL_PCT=40.0

# Options screening
OPTIONS_DTE_MIN=14
OPTIONS_DTE_MAX=45
OPTIONS_DELTA_MIN=0.30
OPTIONS_DELTA_MAX=0.70
OPTIONS_MIN_OI=100
OPTIONS_MIN_VOLUME=10
OPTIONS_MAX_SPREAD_PCT=5.0
OPTIONS_MIN_PRICE=0.50
OPTIONS_MAX_PRICE=50.0

# Greeks / Yahoo / Risk
RISK_FREE_RATE=0.05
YAHOO_ENABLED=true
YAHOO_RETRY_COUNT=5
YAHOO_BACKOFF_BASE=2
MAX_DOLLAR_RISK=50.0
ENVEOF
echo "[OK] .env created."

# ------------------------------------------------------------------
# Generate function_app/local.settings.json
# ------------------------------------------------------------------
echo "Writing function_app/local.settings.json..."
cat > function_app/local.settings.json << JSONEOF
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "python",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "ALPACA_API_KEY": "$ALPACA_KEY",
    "ALPACA_SECRET_KEY": "$ALPACA_SECRET",
    "WEBHOOK_AUTH_TOKEN": "$WEBHOOK_TOKEN",
    "ALPACA_PAPER": "true"
  },
  "Host": {
    "CORS": "*"
  }
}
JSONEOF
echo "[OK] function_app/local.settings.json created."

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
echo
echo "===================================="
echo "  Setup complete!"
echo "===================================="
echo
echo "To launch the dashboard:"
echo "  ./run_dashboard.sh"
echo
echo "To run the trading function locally:"
echo "  ./run_crassus.sh"
echo
echo "To run tests:"
echo "  ./run_tests.sh"
echo
